name: Coverage

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.json'
      - '.github/workflows/coverage.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.json'
      - '.github/workflows/coverage.yml'

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chromium, firefox, webkit ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps ${{ matrix.browser }}
      - run: npm run coverage -- --browser ${{ matrix.browser }}
